### PR TITLE
fix shutdown exception and bump version to 0.1.6

### LINKED ISSUE #3182: Shutting down Logstash with ^C outputs a warning message
Tried with 1.5.0.rc4.snapshot2.tar package with `stdin` input. Started Logstash, trying to stop via `^C`and pressing any key stops LS, bit outputs the warning message. `^D` works fine. 

```
tar xvf logstash-1.5.0.rc4.snapshot2.tar.gz
bin/logstash -e 'input { stdin {} }'

suyog@machine:/tmp/releases/logstash-1.5.0.rc4.snapshot2$ bin/logstash -e 'input { stdin {} }'
Logstash startup completed
abc
{
       "message" => "abc",
      "@version" => "1",
    "@timestamp" => "2015-05-06T20:44:56.577Z",
          "host" => "Suyogs-MacBook-Pro-2.local"
}
^CSIGINT received. Shutting down the pipeline. {:level=>:warn}

Logstash shutdown completed
LogStash::ShutdownSignal: LogStash::ShutdownSignal
       debug? at /tmp/releases/logstash-1.5.0.rc4.snapshot2/vendor/bundle/jruby/1.9/gems/cabin-0.7.1/lib/cabin/mixins/logger.rb:70
  inputworker at /tmp/releases/logstash-1.5.0.rc4.snapshot2/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4.snapshot2-java/lib/logstash/pipeline.rb:181
  start_input at /tmp/releases/logstash-1.5.0.rc4.snapshot2/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4.snapshot2-java/lib/logstash/pipeline.rb:171
```

### PR DESCRIPTION
**Pull request by colinsurprenant**
fixes elastic/logstash#3182

### CODE REVIEW

File: lib/logstash/inputs/stdin.rb [hunk 1]
```diff
@@ -12,14 +13,18 @@ class LogStash::Inputs::Stdin < LogStash::Inputs::Base
 
   default :codec, "line"
 
-  public
+  def initialize(*args)
+    super(*args)
+    @stop_requested = Concurrent::AtomicBoolean.new(false)
+  end
```
Comment (ph) [inline lib/logstash/inputs/stdin.rb:19]: This is the only plugin using the #initialize method, to be consistent we should move that to the #register method?

(don't get me wrong here I would love to see us use the #initialize method instead of register)

File: lib/logstash/inputs/stdin.rb [hunk 2]
```diff
@@ -31,16 +36,21 @@ def run(queue)
         end
       rescue IOError, EOFError, LogStash::ShutdownSignal
         # stdin closed or a requested shutdown
+        @stop_requested.make_true
         break
+      rescue => e
+        # ignore any exception in the shutdown process
+        break if @stop_requested.true?
+        raise(e)
```
Comment (ph) [inline lib/logstash/inputs/stdin.rb:44]: This block of code seems unnecessary to me.

``` ruby
rescue => e
# ignore any exception in the shutdown process
break if @stop_requested.true?
raise(e)
```

If an non-rescued exception is throw it will break out of the while loop?

Comment (ph) [inline lib/logstash/inputs/stdin.rb:44]: Ok you are ignoring exception, its a short circuit.

File: lib/logstash/inputs/stdin.rb (hunk 1 above)
Comment (colinsurprenant) [inline lib/logstash/inputs/stdin.rb:19]: no, initializing instance variable in `initialize` is a lot safer, especially if there is no garentees that the `register` method is called and when. I prefer to leave it there.

Comment (ph) [inline lib/logstash/inputs/stdin.rb:19]: valid comment +1

File: lib/logstash/inputs/stdin.rb (hunk 2 above)
Comment (colinsurprenant) [inline lib/logstash/inputs/stdin.rb:44]: but crash the input plugin and typically restart.

Comment (ph) [inline lib/logstash/inputs/stdin.rb:44]: OK fine by me.

Comment (colinsurprenant) [inline lib/logstash/inputs/stdin.rb:44]: the thing is that the current logic in the pipeline is really not clean so this is a safety. the real refactor will be correctly done in elastic/logstash#3211 and #1

Comment (ph) [inline lib/logstash/inputs/stdin.rb:44]: Yeah with the raise if can happen anywhere

**Comment by ph** [comment]
Fixes the exception issue but we did not add any tests?

**Comment by ph** [comment]
LGTM, merge this away.

**Comment by ph** [comment]
:shipit: :shipit: :shipit:
