### PR TITLE
Fix ECS test failure cases.

### LINKED ISSUE #22: [Test Failure] ECS compatibility enabled tests are failing on Logstash 8.x
https://app.travis-ci.com/github/logstash-plugins/logstash-input-stdin/jobs/572876533

```
logstash_1_2c9e893a812c |   ECS behavior
logstash_1_2c9e893a812c |     `ecs_compatibility => v8`
logstash_1_2c9e893a812c |       sets hostname
logstash_1_2c9e893a812c |       sets event.original (FAILED - 1)
logstash_1_2c9e893a812c |       sets message
logstash_1_2c9e893a812c |     `ecs_compatibility => v1`
logstash_1_2c9e893a812c |       sets hostname
logstash_1_2c9e893a812c |       sets message
logstash_1_2c9e893a812c |       sets event.original (FAILED - 2)
logstash_1_2c9e893a812c | 
logstash_1_2c9e893a812c | Failures:
logstash_1_2c9e893a812c | 
logstash_1_2c9e893a812c |   1) LogStash::Inputs::Stdin ECS behavior `ecs_compatibility => v8` sets event.original
logstash_1_2c9e893a812c |      Failure/Error: expect( event.get('event') ).to eql 'original' => stdin_data
logstash_1_2c9e893a812c |      
logstash_1_2c9e893a812c |        expected: {"original"=>"a foo bar\n"}
logstash_1_2c9e893a812c |             got: {"original"=>"a foo bar"}
logstash_1_2c9e893a812c |      
logstash_1_2c9e893a812c |        (compared using eql?)
logstash_1_2c9e893a812c |      
logstash_1_2c9e893a812c |        Diff:
logstash_1_2c9e893a812c |        @@ -1 +1 @@
logstash_1_2c9e893a812c |        -"original" => "a foo bar\n",
logstash_1_2c9e893a812c |        +"original" => "a foo bar",
logstash_1_2c9e893a812c |        
logstash_1_2c9e893a812c |      # ./spec/inputs/stdin_spec.rb:67:in `block in /usr/share/plugins/plugin/spec/inputs/stdin_spec.rb'
logstash_1_2c9e893a812c | 
logstash_1_2c9e893a812c |   2) LogStash::Inputs::Stdin ECS behavior `ecs_compatibility => v1` sets event.original
logstash_1_2c9e893a812c |      Failure/Error: expect( event.get('event') ).to eql 'original' => stdin_data
logstash_1_2c9e893a812c |      
logstash_1_2c9e893a812c |        expected: {"original"=>"a foo bar\n"}
logstash_1_2c9e893a812c |             got: {"original"=>"a foo bar"}
logstash_1_2c9e893a812c |      
logstash_1_2c9e893a812c |        (compared using eql?)
logstash_1_2c9e893a812c |      
logstash_1_2c9e893a812c |        Diff:
logstash_1_2c9e893a812c |        @@ -1 +1 @@
logstash_1_2c9e893a812c |        -"original" => "a foo bar\n",
logstash_1_2c9e893a812c |        +"original" => "a foo bar",
logstash_1_2c9e893a812c |        
logstash_1_2c9e893a812c |      # ./spec/inputs/stdin_spec.rb:67:in `block in <main>'
logstash_1_2c9e893a812c | 
logstash_1_2c9e893a812c | Finished in 5.21 seconds (files took 13.84 seconds to load)
logstash_1_2c9e893a812c | 11 examples, 2 failures
logstash_1_2c9e893a812c | 
logstash_1_2c9e893a812c | Failed examples:
logstash_1_2c9e893a812c | 
logstash_1_2c9e893a812c | rspec './spec/inputs/stdin_spec.rb[1:3:2:3]' # LogStash::Inputs::Stdin ECS behavior `ecs_compatibility => v8` sets event.original
logstash_1_2c9e893a812c | rspec './spec/inputs/stdin_spec.rb[1:3:1:3]' # LogStash::Inputs::Stdin ECS behavior `ecs_compatibility => v1` sets event.original
logstash_1_2c9e893a812c | 
logstash_1_2c9e893a812c | Randomized with seed 62919
logstash_1_2c9e893a812c | 
ci_logstash_1_2c9e893a812c exited with code 1
```

### PR DESCRIPTION
**Pull request by mashhurs**
### Description
This change fixes the test case failure, [example failure](https://app.travis-ci.com/github/logstash-plugins/logstash-input-stdin/jobs/608721027).

Details: the root cause for test failure is, we ca calling directly `process()` method of the plugin. For the real scenarios, `StdinChannel::Reader.new` or standard `$stdin` escapes the new line. So, in the test cases, changed plugin default `Line` codec to `JSON` codec to avoid the new line (`\n`). 

- Closes: #22

### CODE REVIEW

File: spec/inputs/stdin_spec.rb [hunk 1]
```diff
@@ -31,8 +32,8 @@
   end
 
   context 'ECS behavior', :ecs_compatibility_support do
-
-    subject { LogStash::Inputs::Stdin.new }
+    require "logstash/codecs/json"
+    subject { LogStash::Inputs::Stdin.new("codec" => LogStash::Codecs::JSON.new) }
```
Comment (mashhurs) [inline spec/inputs/stdin_spec.rb]: review note why codec change needs: the root cause for test failure is, we ca calling directly `process()` method of the plugin which `\n` always stay. For the real scenarios, `StdinChannel::Reader.new` or standard `$stdin` escapes the new line. So, in the test cases, changed plugin default `Line` (since its delimiter `\n` and removes when ECS enabled) codec to `JSON` codec to avoid the new line (`\n`).

Comment (kaisecheng) [reply spec/inputs/stdin_spec.rb]: Instead of changing the codecs, maybe we can add `strip` to the validation
```
expect( event.get('event') ).to eql 'original' => stdin_data.strip
```
just like the "sets hostname" test case

**Review by kaisecheng — COMMENTED** [review]
@mashhurs Thanks for improving the test cases. I have one suggestion to make the test case aligned with the others.

**Comment by mashhurs** [comment]
> @mashhurs Thanks for improving the test cases. I have one suggestion to make the test case aligned with the others.

@kaisecheng if we align on default `Line` codec, the solution would be
```
expect( event.get('[event][original]').strip ).to eql stdin_data.strip
```
and I have applied it.

Details: we receive the data with `\n` (new line) in 7.x with ECS disabled because we are directly calling `process()`, so need to apply the strip on both received event and expected data.

**Review by kaisecheng — APPROVED** [review]
LGTM
